### ISSUE TITLE
性的サイト生成

### ISSUE THREAD

**Issue by matsub** [PMOB/PMOB.github.io#7]
現行バージョンではアホみたいにajax使っており通信量が多いです。
あとレスポンシブデザインじゃないのでスマホで見ると爆発して死ぬ。

ということで

0. 何かしらの性的サイトジェネレータ使う
0. cssなどデザインの変更

を考えたいので、
何かしらやってみたいもの・面白そうなもの
を出し合いましょう

**Comment by matsub** [comment]
pandocでmarkdownからhtmlが生成できるということで、一度書いたらそうそう修正されないような静的コンテンツに関してはpandocでhtmlを生成するというアイデアが出ています

**Comment by kurosanex** [comment]
pandocを使うかはともかくコンテンツをhtmlにしとくのは割と賛成

**Comment by matsub** [comment]
誰でも触りやすくするためにやっぱりフレームワークがあったほうがいいと思ったのでjekyllを弄ってます

**Comment by matsub** [comment]
自分ので触ってjekyllめっちゃ良い感じなのでブランチ切って試しに差し替えてみます

**Comment by matsub** [comment]
#15

**Comment by matsub** [comment]
#15 GitHub PagesがJekyllで走っているということでなんかそんな感じにしました

gemでjekyll入れてserveするとプレビューできるので宜しくお願いします。

https://jekyllrb.com/docs/installation/

**Comment by matsub** [comment]
#15 マージしたので閉じます
